### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by SpriteNoobXD** [MoldyGH/VsDave#43] opened 2022-11-14 01:17 UTC
When I try to compile the Dave and Bambi 3.0 source code, it says:

source/PlayState.hx:292: characters 12-24 : Type not found : VideoHandler
source/LoadingState.hx:18: lines 18-226 : ... Defined in this class
source/StoryMenuState.hx:260: characters 17-29 : Type not found : VideoHandler
source/Note.hx:339: characters 18-28 : Class<PlayState> has no field scrollType

**Comment by mayo78** [comment] 2022-11-14 16:45
![Screenshot 2022-11-14 11 44 46 AM](https://user-images.githubusercontent.com/75394229/201717105-db2f3fd6-a9c8-461f-ac01-0707b331d038.png)

**Comment by benjaminpants** [comment] 2022-11-18 18:41
Duplicate of #20

**Closed by benjaminpants** 2022-11-18 18:41 UTC
Labels: bug
