### ISSUE TITLE
Bug Report: can't complie

### ISSUE THREAD

**Issue by imdumlol** [MoldyGH/VsDave#51] opened 2022-11-30 21:19 UTC
source/Main.hx:75: characters 61-65 : Float should be Int
source/Main.hx:75: characters 61-65 : ... For optional function argument 'updateFramerate'
source/Main.hx:75: characters 61-65 : ... For function argument 'child'
source/PlayState.hx:292: characters 12-24 : Type not found : VideoHandler
source/LoadingState.hx:18: lines 18-226 : ... Defined in this class
source/StoryMenuState.hx:260: characters 17-29 : Type not found : VideoHandler
source/CompatWarningState.hx:27: characters 72-73 : Int should be flixel.util.FlxAxes
source/CompatWarningState.hx:27: characters 72-73 : ... For optional function argument 'repeatAxes'
source/Note.hx:339: characters 18-28 : Class<PlayState> has no field scrollType
source/SelectLanguageState.hx:34: characters 70-71 : Int should be flixel.util.FlxAxes
source/SelectLanguageState.hx:34: characters 70-71 : ... For optional function argument 'repeatAxes' 
help??

**Comment by MemeHoovy** [comment] 2022-11-30 21:30
just don't use flixel 5.0.0 & use the git version of hxCodec `haxelib git hxCodec https://github.com/polybiusproxy/hxCodec`

**Comment by imdumlol** [comment] 2022-11-30 21:34
i still have the same error

**Comment by MemeHoovy** [comment] 2022-11-30 21:39
use flixel 4.11.0 `haxelib install flixel 4.11.0`

**Comment by imdumlol** [comment] 2022-11-30 21:42
still have it

**Comment by MemeHoovy** [comment] 2022-11-30 21:43
so you've done both correct?

**Comment by imdumlol** [comment] 2022-11-30 21:43
yea

**Comment by MemeHoovy** [comment] 2022-11-30 21:44
well then idk, that usually fixes the problem

**Comment by imdumlol** [comment] 2022-11-30 21:49
oh ok....

**Comment by benjaminpants** [comment] 2022-12-01 02:07
please stop using the issue tracker as a way to ask for help compiling. closing for being pretty much a duplicate of #20.

**Closed by benjaminpants** 2022-12-01 02:07 UTC
Labels: bug
