### ISSUE TITLE
Bug Report: i cant compile

### ISSUE THREAD

**Issue by MrMichaDaDude** [MoldyGH/VsDave#22] opened 2022-10-17 13:15 UTC
i cant compile cuz it says this
source/PlayState.hx:292: characters 12-24 : Type not found : VideoHandler
source/LoadingState.hx:18: lines 18-226 : ... Defined in this class
source/StoryMenuState.hx:260: characters 17-29 : Type not found : VideoHandler
source/Note.hx:339: characters 18-28 : Class<PlayState> has no field scrollType
please help

**Comment by MoldyGH** [comment] 2022-10-17 13:17
You probably don't have hxCodec installed 

haxelib git hxCodec https://github.com/PolybiusProxy/hxCodec

**Comment by MemeHoovy** [comment] 2022-10-17 13:18
hi moldy!

**Comment by MrMichaDaDude** [comment] 2022-10-17 15:22
> You probably don't have hxCodec installed
> 
> haxelib git hxCodec https://github.com/PolybiusProxy/hxCodec

i try installing with git and it freezes and when i try installing through haxe it says i already have it installed

**Comment by MrMichaDaDude** [comment] 2022-10-17 15:35
> You probably don't have hxCodec installed
> 
> haxelib git hxCodec https://github.com/PolybiusProxy/hxCodec

ya i tried reinstalling, same error message

**Comment by MrMichaDaDude** [comment] 2022-10-17 15:42
> You probably don't have hxCodec installed
> 
> haxelib git hxCodec https://github.com/PolybiusProxy/hxCodec

also your cool

**Comment by benjaminpants** [comment] 2022-10-17 23:40
duplicate of #20

**Closed by benjaminpants** 2022-10-17 23:40 UTC
Labels: question
